### ISSUE TITLE
Set up demo page

### ISSUE THREAD

**Issue by andrewpye** [smile-io/ember-polaris#10]
We should set up the dummy app as a demo page and host it via GitHub pages

**Comment by sivakumar-kailasam** [comment]
How about using https://ember-learn.github.io/ember-cli-addon-docs/?

**Comment by andrewpye** [comment]
@sivakumar-kailasam I gave this a [quick spike](https://github.com/smile-io/ember-polaris/commit/cdef3d71e48c76ebd51d812681c6ae1ae5ff625f) a few months back and hit [an issue](https://github.com/ember-learn/ember-cli-addon-docs/issues/137) with `ember-cli-addon-docs` and ended up moving on to something higher-priority as a result. Never got around to picking this up again since...

**Comment by vladucu** [comment]
would be a perfect solution, I think....at least from what I recall checking it
have you used it Siva? seen a couple of addons using it and having pretty cool docs

**Comment by sivakumar-kailasam** [comment]
We adapted recently on the ember-styleguide. I've been closely watching this, so even if we hit snags, we can get it sorted out.
