### ISSUE TITLE
Changes to underlying data don't trigger `polaris-data-table` cell size recalculation

### ISSUE THREAD

**Issue by andrewpye** [smile-io/ember-polaris#161]
If a `polaris-data-table` is being used to render data and e.g. a new item is added or the content of a cell is updated, the code to set row heights etc. doesn't run. This can leave table row heights too big/small for their content.

We might be able to handle this by bubbling an action from `polaris-data-table/cell`'s `didRender` hook up to the `polaris-data-table` component and triggering the height recalculation from there.

**Comment by vladucu** [comment]
is this a bug in our implementation or in Shopify's implementation too?

**Comment by andrewpye** [comment]
Actually [looks like it](https://codesandbox.io/s/189y72pl2j), yep - opening an issue on Shopify's repo 👍

**Comment by vladucu** [comment]
@tomnez while cleaning up, would you mind quick checking this one too pls?
