### ISSUE TITLE
polaris-text-field prevents click events when losing focus after updating value

### ISSUE THREAD

**Issue by andrewpye** [smile-io/ember-polaris#167]
**Repro steps**
1. Set up a page with a `polaris-text-field` and a `polaris-button` on it.
2. Focus the text field, enter some text and click the button.

**Expected result**
Button action fires.

**Actual result**
Button action does not fire.

I've confirmed that this is _not_ an issue with the original React component.

Example - clicking the page secondary action here should always open a modal, but does not when the text field is focussed and has an updated value:
![polaris-text-field-bug](https://user-images.githubusercontent.com/5737342/45505947-ee235500-b75b-11e8-9752-85852d91f784.gif)

**Comment by vladucu** [comment]
I don't think this is still a thing, closing
