### ISSUE TITLE
Update polaris-breadcrumbs component

### ISSUE THREAD

**Issue by vladucu** [smile-io/ember-polaris#177]
Changes [here](https://github.com/Shopify/polaris/compare/v2.2.0...v2.11.0#diff-85d305f5099f6a7052e1b1bbdb5ea595R5)

**Comment by andrewpye** [comment]
@vladucu maybe worth adding a link to the diff so whoever picks this up can see what needs to be updated?

**Comment by vladucu** [comment]
good point...though it's already picked up 😉

**Comment by vladucu** [comment]
fixed in #179
