### ISSUE TITLE
Implement app provider concept and components

### ISSUE THREAD

**Issue by vladucu** [smile-io/ember-polaris#182]
It's more than 6 months this was released and we still don't have this and hack around it, will give a quick shot at this 
[App Provider](https://polaris.shopify.com/components/structure/app-provider)

**Comment by andrewpye** [comment]
I had a thought about how we could make a generic addon that'd allow us to use React's [`context`](https://reactjs.org/docs/context.html) concept in Ember component trees... wanted just never got the time to give it a try 😞

**Comment by vladucu** [comment]
dump your brain here please

**Comment by andrewpye** [comment]
I didn't have anything concrete, and tbh it'd probably end up relying on private APIs, but the general thinking was to have provider and consumer mixins, with the latter navigating up the target component's hierarchy until it found a component with the provider mixin that offered the right type of context 🤷‍♂️

**Comment by vladucu** [comment]
cool cool, yeah thought about something similar initially
have 1-2 ideas I'll check and then update here with results before starting anything

**Comment by sivakumar-kailasam** [comment]
Provider pattern in react world is a way to achieve dependency injection(DI), so in ember that would translate to having a service along with an initializer that sets this service across components in this addon to achieve the same effect 🙂

**Comment by andrewpye** [comment]
Interesting thought @sivakumar-kailasam, and definitely seems more straightforward and "Ember Way™️"  👍 Would that service _need_ an initializer though, or can't components just grab it via injection themselves?

**Comment by sivakumar-kailasam** [comment]
Not really, they can be authored to inject it themselves as needed. 

Mentioned it since it'd be 1:1 with the react implementation. 

Its similar to how `store` service is injected into all components via an initializer so that they don't have to inject it themselves. A matter of convenience really 🙂But if not too many components need it, we can author it to manually inject it as required.

**Comment by andrewpye** [comment]
Yeah I think injecting it themselves would be preferable, since then it's opt-in (as the React approach seems to be too)

**Comment by vladucu** [comment]
closing this as we have a temp sol for now in #265

**Comment by andrewpye** [comment]
>I had a thought about how we could make a generic addon that'd allow us to use React's context concept in Ember component trees

For posterity, this addon has been hacked together for now: https://github.com/andrewpye/ember-context
