### ISSUE TITLE
Upgrade polaris-checkbox / polaris-choice components

### ISSUE THREAD

**Issue by tomnez** [smile-io/ember-polaris#186]
Minor updates from v2.2 -> v2.11, diff [here](https://github.com/Shopify/polaris/compare/v2.2.0...v2.11.0?diff=split#diff-07693469831f3bf8790b8c358d194d7c)

**Comment by tomnez** [comment]
https://github.com/smile-io/ember-polaris/pull/187

**Comment by vladucu** [comment]
fixed in #187
