### ISSUE TITLE
Pagination - add new attributes

### ISSUE THREAD

**Issue by sivakumar-kailasam** [smile-io/ember-polaris#192]
New `nextKeys`, `previousKeys`, `nextTooltip`, and `previousTooltip` attributes added with some new event listeners to handle keypress events.

**Comment by sivakumar-kailasam** [comment]
Polaris seemed to have rolled out their own [keys enum](https://github.com/Shopify/polaris/blob/master/src/types.ts#L125) & event listener component for  handling the keypress events for the new attributes mentioned in the issue description.

While we could do the same, I feel we'd be better off using [ember-keyboard](https://github.com/patience-tema-baron/ember-keyboard) since the key codes used in it follow browser standards.The addon provides valuable utilties for testing. It also accounts for [software keymaps](https://github.com/patience-tema-baron/ember-keyboard/pull/88) which I dont believe polaris handles at this point.

If this approach sounds good, I'll implement a `key-press-listener` component similar to the one used in the react implementation but using `ember-keyboard` & implement the new attributes.

**Comment by vladucu** [comment]
fixed in #195
