### ISSUE TITLE
Implement polaris tooltip component

### ISSUE THREAD

**Issue by sivakumar-kailasam** [smile-io/ember-polaris#196]
Implement https://polaris.shopify.com/components/overlays/tooltip. 

Related info:
- [react implementation](https://github.com/Shopify/polaris/blob/master/src/components/Tooltip/Tooltip.tsx)
- [original polaris stylesheet](https://github.com/Shopify/polaris/blob/master/src/components/Tooltip/Tooltip.scss)
- [polaris' test suite for tooltip component](https://github.com/Shopify/polaris/blob/master/src/components/Tooltip/tests/Tooltip.test.tsx)

**Comment by vladucu** [comment]
closing this, it's coming _soon_
