### ISSUE TITLE
Create new OptionList component

### ISSUE THREAD

**Issue by tomnez** [smile-io/ember-polaris#235]
New OptionList component as of Polaris 2.3 -

- [Polaris demo and docs](https://polaris.shopify.com/components/lists-and-tables/option-list)
- [Github folder](https://github.com/Shopify/polaris-react/tree/v2.11.0/src/components/OptionList) (v2.11.0)

If our v2.11.0 updates have been merged and released, then this new component can go in master. Otherwise create the component off `dev` branch.

**Comment by vladucu** [comment]
we have this already, closing
