### ISSUE TITLE
Refactor ActionList and sub components

### ISSUE THREAD

**Issue by tomnez** [smile-io/ember-polaris#238]
Our implementation of `polaris-action-list` seems a bit out of date and different from the way the React component is structured.

Our `polaris-action-list/item` component takes only a single `item` object attribute, when it should really be taking item attributes:

- `id`
- `badge`
- `content`
- `url`
- `onAction`
- `icon`
- `image`
- `disabled`
- `external`
- `destructive`
- `ellipsis`
- `active`
- `role`

This is just one example where the components differ, we should check all of them thoroughly. Also some of these attributes we currently don't have implemented so we should add anything that's been missing.

- ActionList [on github](https://github.com/Shopify/polaris-react/tree/master/src/components/ActionList)
- ActionList [reference and docs](https://polaris.shopify.com/components/actions/action-list)

**Comment by vladucu** [comment]
this was fixed at some points, closing
