### ISSUE TITLE
polaris-select selects first option as selected if null value is passed in

### ISSUE THREAD

**Issue by tomnez** [smile-io/ember-polaris#248]
React version properly shows a disabled and selected placeholder if no `value` attribute is passed in:

![polaris](https://user-images.githubusercontent.com/2292367/48027342-89122d00-e116-11e8-886a-e0051894ec0d.gif)

Currently our version will display the first option selected if we don't pass in a `value` - In order to select it you have to select a different option and _then_ select the first option.

![ember-polaris](https://user-images.githubusercontent.com/2292367/48027398-ae9f3680-e116-11e8-9817-43abbb801d64.gif)

**Comment by andrewpye** [comment]
@tomnez this seems to be very closely related to https://github.com/Shopify/polaris-react/issues/496. The consensus there was that we should always be supplying a `value` that matches one of the `options`; by extension I'd think that a fix for this one would be to default the `value` to an empty string instead of `null` (which TypeScript is probably taking care of in the React implementation).

**Comment by tomnez** [comment]
@andrewpye Hm I remember that being the case, but it's still strange that their select _does_ behave correctly when there isn't a value passed in. In the above gif, their placeholder is shown as disabled and selected when a value isn't passed, but _ours_ selects the first.

It seems like at some point their `Select` got fixed even though they decided you should just always pass in an available value (?)

**Comment by andrewpye** [comment]
Does `polaris-select`'s behaviour match if you default `value` to an empty string? That seems to be what's happening in the React [implementation](https://github.com/Shopify/polaris-react/blob/master/src/components/Select/Select.tsx#L90) 🤦‍♂️

**Comment by tomnez** [comment]
Ah you're right, passing an empty String will make it match the React implementation. Closing.

**Comment by andrewpye** [comment]
@tomnez just checked and we're already defaulting `value` to `''`; if we don't pass a `value` at all and have a placeholder, the placeholder should be treated as selected - is that what happens?

**Comment by tomnez** [comment]
Yeah, I think the problem was I was passing in changeset fields that hadn't been given any value yet, so it was set to `undefined` instead of `''`. Passing no `value` at all works, but as mentioned we could do something like `value=(or changeset.value "")` if we need to.

**Comment by andrewpye** [comment]
Gotcha, thanks for clarifying! 👍
