### ISSUE TITLE
How exactly to install and use?

### ISSUE THREAD

**Issue by Lavan01** [smile-io/ember-polaris#639]
I installed ember-polaris using ember-cli, then when I try to use a component in application.hbs, for example:

{{#polaris-button}}
  Block text
{{/polaris-button}}

The Polaris style isn't being implemented when I try to run the ember app.
I'm not very certain about how to use this library.
Thank you.

**Comment by Lavan01** [comment]
I made it to work.
After "npm install node-sass" and changing in the ember-cli-build.js file,

```
const nodeSass = require('node-sass');

module.exports = function(defaults) {
  let app = new EmberApp(defaults, {
    // Add options here
    sassOptions: {
      implementation: nodeSass
    }
  });

```

**Comment by andrewpye** [comment]
Thanks for sharing your experience with us @Lavan01! Pleased to hear you were able to get the addon working 😊 

@vladucu I'm a bit unfamiliar with the requirements for SASS usage here, do you think this is something that we need to address in the readme?

**Comment by vladucu** [comment]
> @vladucu I'm a bit unfamiliar with the requirements for SASS usage here, do you think this is something that we need to address in the readme?

yeah, we should do that
